name: datagrid_simple_sample
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_core: ^28.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0  
  syncfusion_flutter_sliders: ^28.2.12
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
